#!/usr/bin/env sh

# Colors
BACKGROUND=0xff1a1b26
FOREGROUND=0xffc0caf5
BLACK=0xff15161E
RED=0xfff7768e
GREEN=0xff9ece6a
YELLOW=0xffe0af68
BLUE=0xff7aa2f7
MAGENTA=0xffbb9af7
CYAN=0xff7dcfff
WHITE=0xffa9b1d6

BAR_COLOR=$BACKGROUND
ICON_COLOR=$WHITE
LABEL_COLOR=$WHITE
POPUP_BACKGROUND_COLOR=$BLACK
POPUP_BORDER_COLOR=$GREEN
SHADOW_COLOR=$BLACK

PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="FiraCode Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants

PADDINGS=3 # All paddings use this value (icon, label, background and bar paddings)
SEGMENT_SPACING=13 # The spacing between segments

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=3

SHADOW=on
SHADOW_DISTANCE=3
SHADOW_ANGLE=35

# Setting up the general bar appearance and default values
sketchybar --bar     height=32                                           \
                     corner_radius=0                                     \
                     border_width=0                                      \
                     margin=-200                                         \
                     blur_radius=0                                       \
                     position=top                                        \
                     padding_left=4                                      \
                     padding_right=4                                     \
                     color=$BAR_COLOR                                    \
                     topmost=off                                         \
                     font_smoothing=off                                  \
                     y_offset=-32                                        \
                     shadow=off                                          \
                     notch_width=0                                       \
                                                                         \
           --default drawing=on                                          \
                     updates=when_shown                                  \
                     label.font="$FONT:Regular:13.0"                     \
                     icon.font="$FONT:Bold:14.0"                         \
                     icon.color=$ICON_COLOR                              \
                     label.color=$LABEL_COLOR                            \
                     icon.padding_left=$PADDINGS                         \
                     icon.padding_right=$PADDINGS                        \
                     label.padding_left=$PADDINGS                        \
                     label.padding_right=$PADDINGS                       \
                     background.padding_right=$PADDINGS                  \
                     background.padding_left=$PADDINGS                   \
                     popup.background.border_width=$POPUP_BORDER_WIDTH   \
                     popup.background.corner_radius=$POPUP_CORNER_RADIUS \
                     popup.background.border_color=$POPUP_BORDER_COLOR   \
                     popup.background.color=$POPUP_BACKGROUND_COLOR      \
                     popup.background.shadow.drawing=$SHADOW             \
                     icon.shadow.color=$SHADOW_COLOR                     \
                     icon.shadow.distance=$SHADOW_DISTANCE               \
                     icon.shadow.angle=$SHADOW_ANGLE                     \
                     icon.shadow.drawing=$SHADOW                         \
                     label.shadow.color=$SHADOW_COLOR                    \
                     label.shadow.distance=$SHADOW_DISTANCE              \
                     label.shadow.angle=$SHADOW_ANGLE                    \
                     label.shadow.drawing=$SHADOW

sketchybar --add       item               apple.logo left             \
           --set       apple.logo         icon=                      \
                                          label.drawing=off           \
                                          icon.font="$FONT:BOLD:16.0" \
                                          icon.y_offset=2

sketchybar --add event input_source_change AppleSelectedInputSourcesChangedNotification
sketchybar --add       item         input_source left                    \
           --set       input_source script="$PLUGIN_DIR/input_source.sh" \
                                    icon.font="$FONT:BOLD:18.0"          \
                                    icon.y_offset=0                      \
                                    label.drawing=off                    \
           --subscribe input_source input_source_change

sketchybar  --add      item  slack left                    \
            --set      slack                               \
                             update_freq=180               \
                             script="$PLUGIN_DIR/slack.sh" \
                             icon.font="$FONT:BOLD:16.0"   \
           --subscribe slack system_woke

sketchybar --add item task left                         \
           --set task      script="$PLUGIN_DIR/task.sh" \
                           update_freq=120              \
                           background.border_width=0    \
                           icon.font="$FONT:BOLD:16.0"

sketchybar --add       item        application center                                \
           --set       application script="sketchybar --set \$NAME label=\"\$INFO\"" \
                                   label.font="$FONT:BOLD:14.0"   \
           --subscribe application front_app_switched

sketchybar --add item time right                   \
           --set time update_freq=10               \
                      script="$PLUGIN_DIR/time.sh" \
                      icon=""                     \
                      icon.font="$FONT:BOLD:16.0"  \
                      icon.y_offset=0              \
           --add item date right                   \
           --set date update_freq=10               \
                      script="$PLUGIN_DIR/date.sh" \
                      icon.font="$FONT:BOLD:13.0"  \
                      icon=""                     \
                      icon.y_offset=0

sketchybar --add       item    battery right                   \
           --set       battery script="$PLUGIN_DIR/battery.sh" \
                               icon.font="$FONT:BOLD:16.0"     \
                               icon.y_offset=0                 \
                               update_freq=120                 \
           --subscribe battery system_woke power_source_change

sketchybar --add       item    volume right                    \
           --set       volume  script="$PLUGIN_DIR/volume.sh"  \
                               icon.font="$FONT:BOLD:16.0"     \
           --subscribe volume volume_change

sketchybar --add       item    wifi right                     \
           --set       wifi    script="$PLUGIN_DIR/wifi.sh"   \
                               icon.font="$FONT:BOLD:16.0"    \
           --subscribe wifi    wifi_change

############## FINALIZING THE SETUP ##############
sketchybar --update

############## Animation ########################
sketchybar --animate sin 30 --bar y_offset=0 notch_width=200 margin=0 shadow=on

echo "sketchybar configuation loaded.."
