#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp
yabai -m config top_padding 2
yabai -m config bottom_padding 2
yabai -m config left_padding 2
yabai -m config right_padding 2
yabai -m config window_gap 1
yabai -m config window_shadow off
# add 0 padding to the bottom and 30 padding to top of all spaces regardless of the display it belongs to
yabai -m config external_bar all:30:0

yabai -m config window_border                on 
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff9ece6a

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Alacritty Popup$" manage=off

yabai -m rule --add app="^Skype$" manage=off
yabai -m rule --add app="^Zalo$" manage=off
yabai -m rule --add app="^Slack$" manage=off

yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Calculator$" manage=off

yabai -m signal --add event=window_destroyed action="bash $HOME/Workspace/dotfiles/yabai/scripts/window_focus_on_destroy.sh"

echo "yabai configuration loaded.."
