#!/bin/zsh

# Select password using fzf
function fpass() {
  local prompt='Search password: '
  local fzf_cmd="${1-"__fzfp"} --print-query --prompt=\"$prompt\""

  if [ -n "$term" ]; then
    fzf_cmd="$fzf_cmd -q\"$term\""
  fi

  fzf_cmd="$fzf_cmd | tail -n1"

  if [ ! -d $HOME/.password-store ]; then
    e_error "Could not locate password store directory. Please ensure $HOME/.password-store is setup."
    return
  fi

  passfile=$(find -L "$HOME/.password-store" -path '*/.git' -prune -o -iname '*.gpg' -print \
        | sed -e 's/.gpg$//' | sed -e 's/\/Users\/'$(whoami)'\/.password-store\///' \
        | sort \
        | eval "$fzf_cmd" )

  if [ -z "$passfile" ]; then
    e_warning 'No passfile selected.'
    return
  fi

  pass show "$passfile" --clip || return
}
