return {
  mason = {
    package_installed = "◍",
    package_pending = "◍",
    package_uninstalled = "◍",
  },
  diagnostics = {
    error = "",
    warning = "",
    hint = "󰌶",
    info = "",
  },
  barbar = {
    active_button = "󰅖",
    inactive_button = "×",
    modified_button = "●",
    pinned_button = "󰐃",
    separator_left = "▎",
  },
  fzf = {
    win_border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  },
  ibl = {
    char = "▏",
    tab_char = "▏",
  },
  dap = {
    breakpoint = "󰃤",
    disconnect = "",
    pause = "",
    play = "",
    run_last = "",
    step_back = "",
    step_into = "",
    step_out = "",
    step_over = "",
    terminate = "",
    collapsed = "",
    current_frame = "",
    expanded = "",
  },
  telescope = {
    prompt_prefix = " ",
    selection_caret = " ",
  },
  kind = {
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "󰉋",
    Function = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "󰟢",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
  statusline = {
    filetype = {
      sfm = "󰙅",
      fzf = "",
      VimDatabase = "",
      ["git.nvim"] = "",
      diff = "",
      floaterm = "",
      startify = "",
      help = "󰗚",
    },
    buftype = {
      terminal = "",
    },
    git = {
      branch = "󰊢",
    },
    file = {
      default = "",
    },
  },
  gitsigns = {
    add = "│",
    change = "│",
    delete = "_",
    topdelete = "‾",
    changedelete = "~",
    untracked = "┆",
  },
  nvim_ufo = {
    fold_suffix = "󰁂",
  },
  fillchars = {
    foldopen = "",
    foldclose = "",
    foldsep = " ",
    eob = " ",
    fold = " ",
  },
  listchars = {
    tab = "» ",
    eol = "¬",
    extends = "›",
    precedes = "‹",
    nbsp = "␣",
    trail = "·",
  },
}
