require 'themes.colorscheme'

require 'plugins.vim-easymotion'
require 'plugins.vim-startify'
require 'plugins.vim-gitgutter'
require 'plugins.vim-submode'
require 'plugins.vim-fugitive'
require 'plugins.lightline-bufferline'
require 'plugins.fzf'
require 'plugins.clever-f'
require 'plugins.coc'
