# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
if [ -d "/usr/local/opt/llvm/bin/" ]; then
  export PATH=/usr/local/opt/llvm/bin/:$PATH
fi

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="flazz"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
source $ZSH/antigen.zsh
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle MichaelAquilina/zsh-you-should-use
antigen apply

plugins=(
  brew
  git
  vi-mode
  z
  fzf
  asdf
  thefuck
)

source $ZSH/oh-my-zsh.sh

source "${HOME}/.zshrc.local"

for cfg in $DOTFILES/zsh/zshrc.d/*; do
  source $cfg
done

for fn in $DOTFILES/zsh/functions/*; do
  source $fn
done

export PATH=$PATH:$(go env GOPATH)/bin

export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export EDITOR=nvim
export VISUAL="$EDITOR"

if [ -z "$IGNORE_GREETING_MESSAGE" ]
then
  neofetch --ascii "$(echo "Hello Huy Duong.\n\nHave a good day" | cowsay)" | lolcat
fi

eval "$(atuin init zsh --disable-up-arrow)"
eval "$(starship init zsh)"
